FROM ubuntu:22.04

# tag: v0.9.6

COPY utils/apt-install-and-clear.sh /usr/local/bin/apt-install-and-clear

RUN apt-get update --fix-missing

COPY install/ubuntu_setup_tz.sh /install/ubuntu_setup_tz.sh
RUN bash /install/ubuntu_setup_tz.sh

COPY install/ubuntu_install_core.sh /install/ubuntu_install_core.sh
RUN bash /install/ubuntu_install_core.sh

COPY install/ubuntu_install_dev_tools.sh /install/ubuntu_install_dev_tools.sh
RUN bash /install/ubuntu_install_dev_tools.sh

#COPY install/ubuntu_install_cmake_from_source.sh /install/ubuntu_install_cmake_from_source.sh
#RUN bash /install/ubuntu_install_cmake_from_source.sh

COPY install/ubuntu_install_python3.sh /install/ubuntu_install_python3.sh
RUN bash /install/ubuntu_install_python3.sh "3.9"

COPY install/ubuntu_install_tensorflow.sh /install/ubuntu_install_tensorflow.sh
RUN bash /install/ubuntu_install_tensorflow.sh

COPY install/ubuntu_install_tflite.sh /install/ubuntu_install_tflite.sh
RUN bash /install/ubuntu_install_tflite.sh

COPY install/ubuntu_install_onnx.sh /install/ubuntu_install_onnx.sh
RUN bash /install/ubuntu_install_onnx.sh

COPY install/ubuntu_install_torch.sh /install/ubuntu_install_torch.sh
RUN bash /install/ubuntu_install_torch.sh

#COPY install/ubuntu_install_opencv3_from_source.sh /install/ubuntu_install_opencv3_from_source.sh
#RUN bash /install/ubuntu_install_opencv3_from_source.sh

#COPY install/ubuntu_install_boost_from_source.sh /install/ubuntu_install_boost_from_source.sh
#RUN bash /install/ubuntu_install_boost_from_source.sh "1.67.0" "3.9"

#COPY install/ubuntu_install_abseil_from_source.sh /install/ubuntu_install_abseil_from_source.sh
#RUN bash /install/ubuntu_install_abseil_from_source.sh

#COPY install/ubuntu_install_protobuf_from_source.sh /install/ubuntu_install_protobuf_from_source.sh
#RUN bash /install/ubuntu_install_protobuf_from_source.sh

COPY install/ubuntu_install_caffe_deps.sh /install/ubuntu_install_caffe_deps.sh
RUN bash /install/ubuntu_install_caffe_deps.sh

COPY install/ubuntu_install_llvm.sh /install/ubuntu_install_llvm.sh
RUN bash /install/ubuntu_install_llvm.sh 15 16 17

ENV TVM_HOME="/opt/tvm"
ENV TVM_PYTHON_VERSION="3.9"
ENV PYTHONPATH="${TVM_HOME}/python:${PYTHONPATH}"
ARG TVM_BUILD_USE_LLVM="ON"
ARG TVM_BUILD_USE_CUDA="OFF"
ARG TVM_BUILD_USE_CUDNN="OFF"
COPY install/ubuntu_install_tvm_from_source.sh /install/ubuntu_install_tvm_from_source.sh
RUN bash /install/ubuntu_install_tvm_from_source.sh
COPY utils/tvmc.sh /usr/local/bin/tvmc

ENV ONNX_MODIFIER_HOME="/opt/onnx-modifier"
COPY install/ubuntu_install_onnx_modifier_from_source.sh /install/ubuntu_install_onnx_modifier_from_source.sh
RUN bash /install/ubuntu_install_onnx_modifier_from_source.sh
COPY utils/onnx-modifier.sh /usr/local/bin/onnx-modifier

COPY install/ubuntu_install_extra.sh /install/ubuntu_install_extra.sh
RUN bash /install/ubuntu_install_extra.sh

ENV SHELL="/usr/bin/zsh"
COPY install/ubuntu_install_zsh.sh /install/ubuntu_install_zsh.sh
RUN bash /install/ubuntu_install_zsh.sh

ENV LANG=C.UTF-8
COPY install/ubuntu_install_vim.sh /install/ubuntu_install_vim.sh
RUN bash /install/ubuntu_install_vim.sh

RUN git config --global --add safe.directory "*"

ARG HOME="/root"
COPY conf/.vimrc "${HOME}"/.vimrc
COPY conf/.zshrc "${HOME}"/.zshrc
COPY conf/.bashrc "${HOME}"/.bashrc
COPY conf/.tmux.conf "${HOME}"/.tmux.conf

ARG PY3_VERSION="$(python3 --version | awk '{print $2}')"
ARG PY3_MAJOR_VERSION="$(echo "${PY3_VERSION}" | cut -d'.' -f1)"
ARG PY3_MINOR_VERSION="$(echo "${PY3_VERSION}" | cut -d'.' -f2)"
ARG PY3_PATCH_VERSION="$(echo "${PY3_VERSION}" | cut -d'.' -f3)"
ARG PY3_MAJOR_MINOR_VERSION="${PY3_MAJOR_VERSION}.${PY3_MINOR_VERSION}"

ENV THIS_DOCKER_REPOSITORY="https://hub.docker.com/repository/docker/duruyao/vimicro-mc"
ENV THIS_DOCKER_TAG="cpu"
ARG BUILD_DATE
ENV THIS_DOCKER_CREATED="${BUILD_DATE}"
ENV THIS_GIT_REPOSITORY="https://github.com/duruyao/vimicro-ai-mc"
ARG BUILD_TAG
ENV THIS_GIT_TAG="${BUILD_TAG}"
